### ISSUE TITLE
Trailing lines in SQL causes a parse exception.

### ISSUE THREAD

**Issue by nackjicholson** [nackjicholson/aiosql#23]
```python
Python 3.8.5 (default, Jul 27 2020, 08:42:51)
[GCC 10.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import aiosql
>>> import psycopg2
>>> from psycopg2.extras import execute_values
>>> sql_str = """
... -- name: create_schema#
... create table test (id int primary key, v1 int, v2 int);
...
... -- name: insert!
... INSERT INTO test (id, v1, v2) VALUES %s;
...
... -- name: update!
... UPDATE test SET v1 = data.v1 FROM (VALUES %s) AS data (id, v1)
... WHERE test.id = data.id;
...
... -- name: getem
... select * from test order by id;
... """
>>>
>>> queries = aiosql.from_str(sql_str, "psycopg2")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nackjicholson/repos/aiosql/aiosql/aiosql.py", line 83, in from_str
    query_data = query_loader.load_query_data_from_sql(sql)
  File "/home/nackjicholson/repos/aiosql/aiosql/query_loader.py", line 74, in load_query_data_from_sql
    query_data.append(self._make_query_datum(query_sql_str))
  File "/home/nackjicholson/repos/aiosql/aiosql/query_loader.py", line 43, in _make_query_datum
    raise SQLParseException(
aiosql.exceptions.SQLParseException: name must convert to valid python variable, got "create_schema#                                                   ".
```

Kind of hard to tell from that. But the way I copy pasted the lines in created trailing space on the end of the lines that messes up our code. There probably needs to be a regex change, or maybe a `.strip()` call somewhere in `query_loader.py`

**Comment by nackjicholson** [comment]
Done
