### ISSUE TITLE
`ValueError: duplicate parameter name` when the same parameter name appears twice

### ISSUE THREAD

**Issue by vivienm** [nackjicholson/aiosql#83]
aiosql 3.4.0 cannot load SQL queries when the same parameter `:name` appears multiple time. It did work with aiosql 3.3.1.

This can be reproduced with this example:

```python
# aiosql_test.py
import aiosql

sql_str = "-- name: get^\n" "select * from test where foo=:foo and foo=:foo"
aiosql.from_str(sql_str, "aiosqlite")
print("OK")
```

Working with aiosql 3.3.1:

```console
$ pip install "aiosql<3.4.0"
$ python3 aiosql_test.py
OK
```

Failing with aiosql 3.4.0:

```console
$ pip install "aiosql==3.4.0"
$ python3 aiosql_test.py
Traceback (most recent call last):
  File "aiosql_test.py", line 4, in <module>
    aiosql.from_str(sql_str, "aiosqlite")
  File "lib/python3.9/site-packages/aiosql/aiosql.py", line 84, in from_str
    query_data = query_loader.load_query_data_from_sql(sql)
  File "lib/python3.9/site-packages/aiosql/query_loader.py", line 117, in load_query_data_from_sql
    query_data.append(self._make_query_datum(query_sql_str, ns_parts))
  File "lib/python3.9/site-packages/aiosql/query_loader.py", line 27, in _make_query_datum
    signature = self._extract_signature(sql)
  File "lib/python3.9/site-packages/aiosql/query_loader.py", line 103, in _extract_signature
    return inspect.Signature(parameters=[self] + params) if params else None
  File "lib/python3.9/inspect.py", line 2826, in __init__
    raise ValueError(msg)
ValueError: duplicate parameter name: 'foo'
```

**Comment by mitya57** [comment]
This bug prevents us from upgrading to aiosql 3.4.0. So I would be grateful if you make a 3.4.1 release after merging the fix. Thanks in advance!

**Comment by benoitscherrer** [comment]
Same here! 
The new call to `inspect.Signature` just breaks all queries in which a parameters is used multiple times

**Comment by sysid** [comment]
Same here.

**Comment by nackjicholson** [comment]
@seandstewart need some input, maybe some help if this is related to the `inspect.Signature`. Sorry, I haven't had much time to respond to this. Thanks for the help everyone.

**Comment by singlecheeze** [comment]
@vivienm @seandstewart please see the PR #96 that I just created.

Your fix is good and spot on, but it now cascades into another bug that is only present because you fixed the issue above. 

There is a default dict that is a lookup of past placeholders for parameters that now has an `.index()` method called on it that doesn't exist. I assumed the original author of the file never ran into the issue as the bug you solved was always present.

I added the needed dict lookup by query name and then called index on the resulting list in the default dict by var name and everything works well!

**Comment by singlecheeze** [comment]
Without the fix in #96 the error is
```python
/aiosql/adapters/asyncpg.py:42 in process_sql                                                                   │              
                               │                                                                                                                                                         │              
                               │    39 │   │   │   var_name = gd["var_name"]                                                                                                             │              
                               │    40 │   │   │   if var_name in self.var_sorted[query_name]:                                                                                           │              
                               │    41 │   │   │   │   # replacement = f"${self.var_sorted[query_name].index(var_name) + 1}"                                                             │              
                               │ ❱  42 │   │   │   │   replacement = f"${self.var_sorted.index(query_name) + 1}"                                                                         │              
                               │    43 │   │   │   else:                                                                                                                                 │              
                               │    44 │   │   │   │   replacement = f"${len(self.var_sorted[query_name]) + 1}"                                                                          │              
                               │    45 │   │   │   │   self.var_sorted[query_name].append(var_name)                                                                                      │              
                               ╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯              
                               AttributeError: 'collections.defaultdict' object has no attribute 'index'
```

**Comment by nackjicholson** [comment]
@singlecheeze @benji-york @seandstewart Okay, I merged a few #94 and Sean seemingly merged #96.

With those changes are we good to go and can close #84 ?

If so, then I'm going to close this issue too.

**Comment by singlecheeze** [comment]
My #96 supports @vivienm's #84 and that one should be merged if not already as well (It's working fine for me, but I didn't look at the/any tests).

**Comment by nackjicholson** [comment]
@singlecheeze Okay, I see. Thanks for the clarification. I'll take a good look at #84 then.
